### ISSUE TITLE
Unable to use latest balenaEtcher

### ISSUE THREAD

**Issue by denzilferreira** [meisenzahl/elementary-os-unofficial#2]
For some weird reason, I always get a message that the xz is corrupted. Any ideas?

**Comment by meisenzahl** [comment]
I generate a checksum for each release. Did you verify that your download matches that checksum?

**Comment by denzilferreira** [comment]
Yes, it matched with md5sum file.xz :-/ I downloaded the file 2/3 times,
same result. Maybe the uploaded file was corrupted?

Denzil

**Comment by meisenzahl** [comment]
Which release are you trying to flash? Which version of Etcher do you use?

**Comment by denzilferreira** [comment]
Both latest, 4th release of your image and downloaded Etcher yesterday
(AppImage).

Denzil

**Comment by denzilferreira** [comment]
![Screenshot from 2019-12-07 14-30-52](https://user-images.githubusercontent.com/8342829/70374700-482eae00-18fe-11ea-87fc-b5b5e3a54471.png)

Same issue :-/ I'll try some other app.

**Comment by denzilferreira** [comment]
I've tried:
- uncompress xz, which worked and I have an img without issue
- tried again balena, same error
- will try now using dd: dd if=elementaryos-hera-arm64+raspi4.20191207.img of=/dev/mmcblk0

I'm not sure why this is happening. Could be that I'm using Fedora as my main OS in the laptop. I'll let you know if DD was able to restore the img to the sdcard and boot from it.

**Comment by denzilferreira** [comment]
I can confirm DD worked and booted! Must be a bug of Etcher on Fedora 31...
