### ISSUE TITLE
PAYWALLS ON OPEN SOURCE SOFTWARE ARE FUNDAMENTALLY WRONG

### ISSUE THREAD

**Issue by couchsweetpotato** [meisenzahl/elementary-os-unofficial#9]
BAD *bonk*

**Comment by meisenzahl** [comment]
This repository is not related to the elementary project. As the README says:

> # elementary OS unofficial builds
> ⚠️ **The builds are not officialy supported by the elementary project** ⚠️
> To download the official version visit [https://elementary.io/](https://elementary.io/)

So, unfortunately, I'm not sure what you're trying to tell me.
